### ISSUE TITLE
Get error when I run lios  after installed it in Ubuntu 18.04 LTS use git and python3

### ISSUE THREAD

**Issue by yuxing007** [Nalin-x-Linux/lios-3#8]
Hello, after I installed lios in Ubuntu18.04 use git and python3 , I run lios in shell as root , I get error as bellow:

`/usr/local/lib/python3.6/dist-packages/lios/ui/gtk/text_view.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/lib/python3.6/dist-packages/lios/ui/gtk/print_dialog.py:23: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/local/lib/python3.6/dist-packages/lios/cam.py:19: PyGIWarning: GstVideo was imported without specifying a version first. Use gi.require_version('GstVideo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkX11, GstVideo
/usr/local/lib/python3.6/dist-packages/lios/ui/gtk/terminal.py:21: PyGIWarning: Vte was imported without specifying a version first. Use gi.require_version('Vte', '2.91') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Vte

(lios:19607): Gtk-WARNING **: 23:58:52.428: Cannot connect attribute 'text' for cell renderer class 'lios+ui+gtk+tree_view+CellRendererToggle' since attribute does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/lios/main.py", line 1329, in make_preferences_effective
    self.dict = dictionary.Dict(dictionary.dictionary_language_dict[languages[self.preferences.language]])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/lios", line 8, in <module>
    linux_intelligent_ocr_solution()
  File "/usr/local/lib/python3.6/dist-packages/lios/main.py", line 342, in __init__
    self.make_preferences_effective()
  File "/usr/local/lib/python3.6/dist-packages/lios/main.py", line 1350, in make_preferences_effective
    pacman -S aspell-fr""").format(languages[self.preferences.language]))
IndexError: list index out of range`

**Comment by yuxing007** [comment]
python3 setup.py install --install-data=/usr
After I use the method above to install lios, and get the error above, I use `sudo apt-get install lios` and then run it use 'sudo lios' , but I get the error below:

`/usr/local/lib/python3.5/dist-packages/lios/ui/gtk/text_view.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/lib/python3.5/dist-packages/lios/ui/gtk/print_dialog.py:23: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/local/lib/python3.5/dist-packages/lios/cam.py:19: PyGIWarning: GstVideo was imported without specifying a version first. Use gi.require_version('GstVideo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkX11, GstVideo
/usr/local/lib/python3.5/dist-packages/lios/ui/gtk/terminal.py:21: PyGIWarning: Vte was imported without specifying a version first. Use gi.require_version('Vte', '2.91') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Vte

(lios:3634): Gtk-WARNING **: Cannot connect attribute 'text' for cell renderer class 'lios+ui+gtk+tree_view+CellRendererToggle' since attribute does not exist
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
update_scanner_list Started
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lios/main.py", line 651, in <lambda>
    child_conn.send(tuple(self.available_scanner_driver_list[self.preferences.scan_driver].get_available_devices()))),
IndexError: list index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lios/main.py", line 659, in update_scanner_list
    driver = self.available_scanner_driver_list[self.preferences.scan_driver]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lios/main.py", line 688, in update_scanner_list
    self.notify_information(ex,0)
  File "/usr/local/lib/python3.5/dist-packages/lios/main.py", line 363, in notify_information
    self.statusbar.set_text(text)
  File "/usr/local/lib/python3.5/dist-packages/lios/ui/gtk/widget.py", line 212, in set_text
    self.label.set_text(text)
TypeError: Must be string, not IndexError
`

**Comment by 503Dev** [comment]
I get the exact same error, I tried reinstalling gir1.2-gst-plugins-base-1.0 which did not help.

**Comment by yuxing007** [comment]
Hello, I think I have resolved this problem: After we installed tesseract , we have to add 
`export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata `
to /etc/profile and source it as root , then we can use sudo lios

**Comment by 503Dev** [comment]
@yuxing007 Thanks for trying to help! I tried that, I just edited my /etc/profile and added the export to the bottom then I did:

sudo -s 
source /etc/profile

I still get an error though,   File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

**Comment by 503Dev** [comment]
Ubuntu 16.04 - installing the following package fixed the above error: sudo apt-get install gir1.2-vte-2.91

However, the interface loads incorrectly.  All the icons are just cancel symbols and the interface is hardly usable. :-(

**Comment by yuxing007** [comment]
I am sorry , I forgot to tell you I have changed the code which is ：
`/usr/local/lib/python3.6/dist-packages/lios/main.py`
Ln:1332`		if (self.old_language != self.preferences.language):`
to
`		if (self.old_language == self.preferences.language):`
and add a code below to ln:1371
`self.dict = dictionary.Dict("en")`

this is just skip the error before, but not really resolve the problem and trigger another problem， so I uninstall the git lios and use the command : 
`sudo apt-get install lios`
to install and  run lios .

**Comment by Nalin-x-Linux** [comment]
The bug is fixed see following commits 
1 https://github.com/Nalin-x-Linux/lios-3/commit/a5e8d8a1dac57c69c9e713b241e87ab3b3fc1379
2 https://github.com/Nalin-x-Linux/lios-3/commit/d40c7db5b08558e816a143817f75f513a521e543
Thanking you Nalin.

**Comment by BASIC1978** [comment]
xubuntu 22.04

Gtk-WARNING **: 23:58:52.428: Cannot connect attribute 'text' for cell renderer class 'lios+ui+gtk+tree_view+CellRendererToggle' since attribute does not exist

Fixed by adding path to /usr/local/lib/python3.10/dist-packages/lios/ocr/ocr_engine_tesseract.py

TESSDATA_POSSIBLE_PATHS

left other paths intact and added:

"/usr/share/tesseract-ocr/5/tessdata"

Worked for me. Lios launched normally.
